const skills = [
  {
    title: "Frontend",
    skills: [
      "HTML5",
      "CSS3",
      "JavaScript",
      "TypeScript",
      "React",
      "Next.js",
      "Netlify",
      "Vercel",
      "Tailwindcss",
      "Material-UI",
      "Bootstrap",
      "Chakra-UI",
      "Styled-Components",
      "Redux",
      "Redux-Toolkit",
      "RTK Query",
      "Context API",
      "Axios",
      "Socket.io-client",
      "Framer-Motion",
      "React-Router",
      "React-Hook-Form",
      "HTML-React-Parser",
      "Redux-Persist",
      "Emailjs",
      "ReactChartJS",
      "Prettier",
    ],
  },
  {
    title: "Backend",
    skills: [
      "Node.js",
      "Express",
      "MongoDB",
      "Appwrite",
      "JWT",
      "REST API",
      "HeroKu",
      "Render",
      "DigitalOcean",
      "Nodemon",
      "Mongoose",
      "Multer",
      "Cloudinary",
      "Dotenv",
      "Cors",
      "Cookie-Parser",
      "Bcrypt",
      "Express-Validator",
      "Socket.io",
    ],
  },
  {
    title: "Tools",
    skills: [
      "Git",
      "GitHub",
      "VS Code",
      "Replit",
      "Figma",
      "Postman",
      "MongoDB Compass",
      "Putty",
      "FileZilla",
    ],
  },
];

export default skills;
